runtime: python37  # specify the python version here
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
entrypoint: uwsgi --http :$PORT --wsgi-file app.py --callable app
